### ISSUE TITLE
Update to angular v17

### ISSUE THREAD

**Issue by BePo65** [ngehlert/ngx-rerender#1]
It would be nice, if the project could be updated to be used with angular v17 (that is what I use in my current project 😄 ).

Should / could I prepare a pr?

**Comment by ngehlert** [comment]
I will do during this week

**Comment by ngehlert** [comment]
bumped the version. angular 17 should work with 1.3.0 now (it should've worked before as well already)

Let me know if you have any problems

cheers :)
