### ISSUE TITLE
publishing v1.3.0 to npmjs used source files instead of dist files

### ISSUE THREAD

**Issue by BePo65** [ngehlert/ngx-rerender#2]
It looks like you used the source directory instead of the dist directory when publishing v1.3.0 to npmjs.
This can be verified by looking onto the [source in npmjs](https://www.npmjs.com/package/ngx-rerender?activeTab=code).

Please republish from the dist directory.

BTW the version 1.3.0 in the main branch is missing the tag '1.3.0' too 😄

**Comment by ngehlert** [comment]
Hi @BePo65 
Sorry messed up the 1.3.0 release there 😅 Thanks for noticing.
Just published a 1.4.0 release should work now :)
